### ISSUE TITLE
config.yaml文件与一些bug

### ISSUE THREAD

**Issue by lyb18758** [SJTU-DeepVisionLab/PosFormer#2]
请问readme中提到训练需要的配置文件config.yaml会公布吗
另一些预训练出现的bug
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    trainer_defaults={"plugins": DDPPlugin(find_unused_parameters=True)},
  File "/home/lyb/miniconda3/envs/pf/lib/python3.7/site-packages/pytorch_lightning/utilities/cli.py", line 278, in __init__
    self.add_core_arguments_to_parser()
  File "/home/lyb/miniconda3/envs/pf/lib/python3.7/site-packages/pytorch_lightning/utilities/cli.py", line 306, in add_core_arguments_to_parser
    self.parser.set_defaults(trainer_defaults)
  File "/home/lyb/miniconda3/envs/pf/lib/python3.7/site-packages/jsonargparse/_core.py", line 902, in set_defaults
    default = action.normalize_default(default)
  File "/home/lyb/miniconda3/envs/pf/lib/python3.7/site-packages/jsonargparse/_typehints.py", line 243, in normalize_default
    raise ValueError("Subclass types require as default either a dict with class_path or a lazy instance.")
ValueError: Subclass types require as default either a dict with class_path or a lazy instance.
还望解答，谢谢

**Comment by lacayqwq** [comment]
Apologies for the misnaming error; in actuality, config_test.yaml is indeed the configuration file we will ultimately be using, and we will rectify this in a forthcoming update.
We will promptly investigate and endeavor to rectify the bug you encounter, be it a code error. Thank you for your attention.

**Comment by zengyangzang** [comment]
Looking forward to the update！I encountered the same bug

**Comment by lacayqwq** [comment]
I'm very sorry for not responding sooner. Could you please share your environment list with me, especially the version of `jsonargparse`? This would be really helpful for me in resolving this issue. Thank you!

----- 原始邮件 -----
发件人: "zengyangzang" ***@***.***>
收件人: "SJTU-DeepVisionLab/PosFormer" ***@***.***>
抄送: "Chengyu Lin" ***@***.***>, "Comment" ***@***.***>
发送时间: 星期三, 2024年 8 月 14日 下午 8:47:01
主题: Re: [SJTU-DeepVisionLab/PosFormer] config.yaml文件与一些bug (Issue #2)

Looking forward to the update！I encountered the same bug

**Comment by lyb18758** [comment]
感谢回复，这是服务器的环境
absl-py                  2.1.0
aiohttp                  3.8.6
aiosignal                1.3.1
async-timeout            4.0.3
asynctest                0.13.0
attrs                    23.2.0
cachetools               5.4.0
certifi                  2022.12.7
charset-normalizer       3.3.2
einops                   0.6.1
fire                     0.6.0
frozenlist               1.3.3
fsspec                   2023.1.0
future                   1.0.0
google-auth              2.32.0
google-auth-oauthlib     0.4.6
grpcio                   1.62.2
idna                     3.7
importlib-metadata       6.7.0
jsonargparse             4.32.0
lightning-lite           1.8.0
lightning-utilities      0.3.0
Markdown                 3.4.4
MarkupSafe               2.1.5
multidict                6.0.5
numpy                    1.21.6
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
oauthlib                 3.2.2
opencv-python            4.10.0.84
packaging                24.0
pandoc                   2.3
Pillow                   9.5.0
pip                      22.3.1
plumbum                  1.8.3
ply                      3.11
protobuf                 3.20.3
pyasn1                   0.5.1
pyasn1-modules           0.3.0
pyDeprecate              0.3.1
pytorch-lightning        1.4.0
PyYAML                   6.0.1
requests                 2.31.0
requests-oauthlib        2.0.0
rsa                      4.9
setuptools               65.6.3
six                      1.16.0
tensorboard              2.11.2
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
termcolor                2.3.0
torch                    1.13.1
torchmetrics             0.5.0
torchvision              0.14.1
tqdm                     4.66.4
typing_extensions        4.7.1
urllib3                  1.26.15
vision                   1.0.0
Werkzeug                 2.2.3
wheel                    0.38.4
yarl                     1.9.4
zipp                     3.15.0

**Comment by lacayqwq** [comment]
Thank you for your message. It seems that there are some differences between our experimental environment and yours (pytorch-lightning==1.4.9, jsonargparse==3.17.0). As you may know, these are frameworks that update frequently and often have limited backward compatibility. You can try modifying your environment configuration, or simply update line 29 in train.py to:
```python
trainer_defaults={"plugins": {"class_path": "pytorch_lightning.plugins.DDPPlugin", "init_args": {"find_unused_parameters": True}}}
```
I cannot guarantee that this will completely resolve your issue.

**Comment by lacayqwq** [comment]
A feasible list of environments：
```
Package                        Version
------------------------------ --------------------
absl-py                        1.1.0
aiohttp                        3.9.1
aiosignal                      1.3.1
anyio                          3.6.1
argon2-cffi                    21.3.0
argon2-cffi-bindings           21.2.0
asttokens                      2.0.5
async-timeout                  4.0.3
attrs                          21.4.0
Babel                          2.10.3
backcall                       0.2.0
beautifulsoup4                 4.11.1
bleach                         5.0.0
boltons                        23.1.1
brotlipy                       0.7.0
cachetools                     5.2.0
certifi                        2023.11.17
cffi                           1.14.6
chardet                        4.0.0
click                          8.1.7
conda                          23.5.2
conda-package-handling         1.7.3
cryptography                   3.4.7
cycler                         0.11.0
debugpy                        1.6.0
decorator                      5.1.1
defusedxml                     0.7.1
einops                         0.3.0
entrypoints                    0.4
executing                      0.8.3
fastjsonschema                 2.15.3
fonttools                      4.33.3
frozenlist                     1.4.0
fsspec                         2023.12.2
future                         0.18.3
google-auth                    2.8.0
google-auth-oauthlib           0.4.6
grpcio                         1.46.3
idna                           2.10
importlib-metadata             4.11.4
importlib-resources            5.8.0
ipykernel                      6.15.0
ipython                        8.4.0
ipython-genutils               0.2.0
ipywidgets                     7.7.0
jedi                           0.18.1
Jinja2                         3.1.2
json5                          0.9.8
jsonargparse                   3.17.0
jsonpatch                      1.33
jsonpointer                    2.4
jsonschema                     4.6.0
jupyter-client                 7.3.4
jupyter-core                   4.10.0
jupyter-server                 1.17.1
jupyterlab                     3.4.3
jupyterlab-language-pack-zh-CN 3.4.post1
jupyterlab-pygments            0.2.2
jupyterlab-server              2.14.0
jupyterlab-widgets             1.1.0
kiwisolver                     1.4.3
lightning-utilities            0.10.0
lxml                           5.1.0
Markdown                       3.3.7
MarkupSafe                     2.1.1
matplotlib                     3.5.2
matplotlib-inline              0.1.3
mistune                        0.8.4
multidict                      6.0.4
nbclassic                      0.3.7
nbclient                       0.6.4
nbconvert                      6.5.0
nbformat                       5.4.0
nest-asyncio                   1.5.5
notebook                       6.4.12
notebook-shim                  0.1.0
numpy                          1.22.4
oauthlib                       3.2.0
opencv-python                  4.8.1.78
packaging                      23.2
pandocfilters                  1.5.0
parso                          0.8.3
pexpect                        4.8.0
pickleshare                    0.7.5
Pillow                         9.1.1
pip                            21.1.3
pluggy                         1.3.0
plumbum                        1.8.2
ply                            3.11
prometheus-client              0.14.1
prompt-toolkit                 3.0.29
protobuf                       3.19.4
psutil                         5.9.1
ptyprocess                     0.7.0
pure-eval                      0.2.2
pyasn1                         0.4.8
pyasn1-modules                 0.2.8
pycosat                        0.6.3
pycparser                      2.20
pyDeprecate                    0.3.1
Pygments                       2.12.0
pyOpenSSL                      20.0.1
pyparsing                      3.0.9
pyrsistent                     0.18.1
PySocks                        1.7.1
python-dateutil                2.8.2
pytorch-lightning              1.4.9
pytz                           2022.1
PyYAML                         6.0.1
pyzmq                          23.2.0
requests                       2.25.1
requests-oauthlib              1.3.1
rsa                            4.8
ruamel-yaml-conda              0.15.100
ruamel.yaml                    0.17.10
ruamel.yaml.clib               0.2.2
Send2Trash                     1.8.0
setuptools                     52.0.0.post20210125
six                            1.16.0
sniffio                        1.2.0
soupsieve                      2.3.2.post1
stack-data                     0.3.0
supervisor                     4.2.4
tensorboard                    2.9.1
tensorboard-data-server        0.6.1
tensorboard-plugin-wit         1.8.1
terminado                      0.15.0
thop                           0.1.1.post2403040100
tinycss2                       1.1.1
toolz                          0.12.0
torch                          1.11.0+cu113
torchmetrics                   0.6.0
torchvision                    0.12.0+cu113
tornado                        6.1
tqdm                           4.61.2
traitlets                      5.3.0
typer                          0.9.0
typing-extensions              4.2.0
urllib3                        1.26.6
wcwidth                        0.2.5
webencodings                   0.5.1
websocket-client               1.3.3
Werkzeug                       2.1.2
wheel                          0.36.2
widgetsnbextension             3.6.0
yarl                           1.9.4
zipp                           3.8.0
```

**Comment by ningyuv** [comment]
pytorch-lightning 1.4.9 released at Sep 30, 2021
The version of jsonargparse at that time was 3.19
so
`pip install jsonargparse[signatures]==3.19`
